CREATE TABLE IF NOT EXISTS syllabuses (
  id VARCHAR(36) PRIMARY KEY NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  topics JSON NOT NULL,
  exam_date DATE NULL,
  total_topics INT DEFAULT 0,
  covered_topics INT DEFAULT 0,
  document_id VARCHAR(36) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
