CREATE TABLE IF NOT EXISTS study_rooms (
  id VARCHAR(36) PRIMARY KEY NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  syllabus_id VARCHAR(36) NULL,
  name VARCHAR(255) NOT NULL,
  subject VARCHAR(255) NULL,
  color VARCHAR(7) NULL,
  deleted_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (syllabus_id) REFERENCES syllabuses(id) ON DELETE SET NULL
);
