CREATE TABLE IF NOT EXISTS summaries (
  id VARCHAR(36) PRIMARY KEY NOT NULL,
  document_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  room_id VARCHAR(36) NULL,
  content JSON NOT NULL,
  model_used VARCHAR(100) NOT NULL,
  tokens_used INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (room_id) REFERENCES study_rooms(id) ON DELETE SET NULL
);
