CREATE TABLE IF NOT EXISTS topic_mastery (
  id VARCHAR(36) PRIMARY KEY NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  syllabus_id VARCHAR(36) NOT NULL,
  topic_name VARCHAR(255) NOT NULL,
  mastery_score DECIMAL(5,2) DEFAULT 0.00,
  quiz_accuracy DECIMAL(5,2) DEFAULT 0.00,
  review_count INT DEFAULT 0,
  weak_flag TINYINT(1) DEFAULT 0,
  last_assessed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (syllabus_id) REFERENCES syllabuses(id) ON DELETE CASCADE
);
